server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: procesamiento-lenguaje-natural
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  level:
    root: INFO
    com.pln: DEBUG
